// <auto-generated />
using System;
using System.Collections.Generic;
using AspireShowcase.BusinessSetup;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspireShowcase.BusinessSetup.Migrations
{
    [DbContext(typeof(BusinessSetupDbContext))]
    [Migration("20261005194149_AddStaff")]
    partial class AddStaff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("business_setup")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspireShowcase.BusinessSetup.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasDatabaseName("IX_Businesses_OwnerId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Businesses_Slug");

                    b.ToTable("Businesses", "business_setup");
                });

            modelBuilder.Entity("AspireShowcase.BusinessSetup.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "AspireShowcase.BusinessSetup.Service.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character(3)")
                                .HasColumnName("PriceCurrency")
                                .IsFixedLength();
                        });

                    b.HasKey("Id");

                    b.HasIndex("BusinessId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Services_BusinessId_Name");

                    b.ToTable("Services", "business_setup");
                });

            modelBuilder.Entity("AspireShowcase.BusinessSetup.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DoesAllServices")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.PrimitiveCollection<Guid[]>("ServiceIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_StaffMembers_BusinessId_Name");

                    b.ToTable("StaffMembers", "business_setup");
                });

            modelBuilder.Entity("AspireShowcase.BusinessSetup.Service", b =>
                {
                    b.HasOne("AspireShowcase.BusinessSetup.Business", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AspireShowcase.BusinessSetup.StaffMember", b =>
                {
                    b.HasOne("AspireShowcase.BusinessSetup.Business", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
